### ISSUE TITLE
File.save issue

### ISSUE THREAD

**Issue by ChrisDarke** [kylebrowning/drupal-ios-sdk#1]
Hi Kyle, 
So bumped into a problem with file.save, when running the operation from iOS, we don't get any data returned, so have no access to the fid and the file doesn't appear to be saved. 
Is there something custom in your Services module, other than the Plist Server? We have the file service modules installed.
Using the example app, using the default url (demo.kylebrowning.com) everything works fine, but using our server it doesn't work. So it doesn't appear to be a problem in the iOS code, it's something in the server. We have everything set up as far as I can see described in the readme, and other operations do work (node.save etc).
If there is nothing else custom can you release your module versions?

Many Thanks,
Chris Darke

**Comment by kylebrowning** [comment]
Hey Chris,

Can you help me help you a bit here? Update to the latest Plist_server module, and turn debugging on. Then goto admin/reports/dblog and see if the data you are submitting is correct.

Also can I see an NSLog(@"%@", fileObject] of the DIOSFile object. 

Are you not getting ANY response from the server? and No errors on the reports page?

Im around feel free to reply to this issue.

**Comment by ChrisDarke** [comment]
Hi Kyle, thanks for your quick reply, just collating that information, will send it over in a moment.

**Comment by ChrisDarke** [comment]
Right, with the latest version of Plist I get a problem, it fails rather miserably, which is why I was running a previous version (1.7). The error I get is this:

Fatal error: Uncaught exception 'IOException' in /home/elgatome/cr_sandbox/sites/all/libraries/cfpropertylist/IOException.php:85 Stack trace: #0 /home/elgatome/cr_sandbox/sites/all/libraries/cfpropertylist/CFBinaryPropertyList.php(387): IOException::readError('') #1 /home/elgatome/cr_sandbox/sites/all/libraries/cfpropertylist/CFBinaryPropertyList.php(442): CFBinaryPropertyList->readBinaryObject() #2 /home/elgatome/cr_sandbox/sites/all/libraries/cfpropertylist/CFBinaryPropertyList.php(491): CFBinaryPropertyList->readBinaryObjectAt(1) #3 /home/elgatome/cr_sandbox/sites/all/libraries/cfpropertylist/CFBinaryPropertyList.php(516): CFBinaryPropertyList->parseBinaryString() #4 /home/elgatome/cr_sandbox/sites/all/libraries/cfpropertylist/CFBinaryPropertyList.php(503): CFBinaryPropertyList->parseBinary('') #5 /home/elgatome/cr_sandbox/sites/all/modules/contrib/services/servers/plist_server/plist_server.module(65): CFBinaryPropertyList->readBinaryStream(Resource id #264) #6 /home/elgatome/cr_sandbox/includes/module.inc(462): plist_ in /home/elgatome/cr_sandbox/sites/all/libraries/cfpropertylist/IOException.php on line 85

Ever seen that before? I figured it was just 'one of those things' and ran with the previous version of Plist Server as it was working sucessfully for all other operations.

**Comment by kylebrowning** [comment]
Are you also using the latest Drupal-ios-sdk? It sounds like when I switching to Binary your drupal-ios-sdk didnt get updated. Try updating that to the latest of that as well.

**Comment by kylebrowning** [comment]
s/switching/switched.

Are you on IRC? I can work more closely with you if you join #drupal-services

**Comment by ChrisDarke** [comment]
We were using the SDK from about a few weeks ago, but Im getting my iOS dev to try the latest version. And no, im not on IRC, got skype though. In any case, the latest version of the PList Server just screws things up. I will revert to 1.7 for now.

**Comment by kylebrowning** [comment]
Ok, I am on skype, name is nomspes.

The latest version of plist_server is incompatible with older versions of drupal-ios-sdk. Both need to be up to date. The versions that existed at 1.7 are certainly not as stable as 1.12

**Comment by ChrisDarke** [comment]
OK so turns out we needed to update to the latest version of Plist server (1.13), the latest version of the SDK, and enable System services, and allow the auth key access to system.connect

:)

Thanks Kyle!

**Comment by ChrisDarke** [comment]
Closing issue
