### ISSUE TITLE
Migration to AFNetworking 2.0

### ISSUE THREAD

**Issue by hernangomez** [kylebrowning/drupal-ios-sdk#101]
After the evolution of AFNetworking to 2.0, the AFHTTPClient has been split into a few pieces : AFHTTPRequestOperationManager & AFHTTPSessionManager.
is there a plan to upgrade to AFNetworking 2.0 or using version 1.3.3 will be the only way?
Thanks

Ref: https://github.com/AFNetworking/AFNetworking/wiki/AFNetworking-2.0-Migration-Guide

**Comment by TomKremer** [comment]
Would be great if someone could make it compatible with AFNetworking 2.0!

**Comment by avaan** [comment]
I tried to upgrade this to compatible with AFNetworking 2.0 but without any success :(.  If it  upgraded to AfNetworking 2.0 it will be more helpful.

**Comment by TomKremer** [comment]
Give this a try and let me know if you have problems: https://github.com/TomKremer/drupal-ios-sdk

**Comment by darthmario** [comment]
@TomKremer going to give it a try and will let you know how it goes.

**Comment by kylebrowning** [comment]
@TomKremer  has done this, and has now been merged.
