### ISSUE TITLE
Sessions

### ISSUE THREAD

**Issue by devel2014drupal** [kylebrowning/drupal-ios-sdk#103]
Hi guys,
I am having hard time understanding authentication. 
I am using the DIOSuser.h to login i get the session id and session name.

I dont see we are using the returned information to carry the rest of operation.

Shouldn't there be a sesionsID or session name we should pass  in NodeSave or any other operations 
how does the authenticated process is integrated with the rest of things we can do with this SDK.

Thanks

**Comment by devel2014drupal** [comment]
As per the documentation i initialized the session 
DIOSSession\* session = [DIOSSession sharedOauthSessionWithURL:kDIOSURL consumerKey:kDIOSConsumerKey secret:kDIOSSecretKey];

The I tried to do DIOSNode nodeSave
and i got the 500 error code. 

is there anything we need to do after doing the 2 legged authentication. 
if i allow anonymous users to do node save i can save the node so right now i have disabled that portion and 
trying to authenticate using 2 legged OAuth and see if the code can post. 

Any help would be appreciated i been searching for answers for almost a week.

**Comment by devel2014drupal** [comment]
shouldn't have clsoed woops

**Comment by kylebrowning** [comment]
Sorry for the late reply. 

I do believe that you need to get the CSRF token, but a 500 response is a FATAL error, do you have any more information.

PLease re-open this ticket if you're still having this issue.
