### ISSUE TITLE
CSRF Validation failed ! 

### ISSUE THREAD

**Issue by paewrblue** [kylebrowning/drupal-ios-sdk#106]
I managed to do the login and register, but  After logging and when I wanna perform any tasks such as Changing Password, Logout. I always get 401 error which is associated with CSRF Validation failed.  After doing some research I found that after the Service 3.4 has been released, the user is required to send the token header along any call of the request. 

Please help

**Comment by paewrblue** [comment]
The problem went away after turning of the session authentication but I have to keep that authentication on !!! Is there a way for me to fix this issue.

**Comment by bessonette** [comment]
@paewrblue Did you find a solution to this? I see the DIOSCSRFAFHTTPClient.h and DIOSCSRFAFHTTPClient.m files, but I'm not sure what to make of them.

**Comment by paewrblue** [comment]
@bessonette  I've fixed the problem now, by fixing up the code in AFHTTPCLIENT to make it to get the Token and send that CSRF token back to the server whenever the requests such as post, delete are fired. Basically, you just replace the code in AFHTTPCLIENT with the code from DIOSCSRFAFHTTPClient.h and DIOSCSRFAFHTTPClient.m.

**Comment by isaac99** [comment]
Im running into the same problem but I dont really understand what you mean by replace the code in AFHTTPClient with the code from DIOSCSRFAFHTTPClient. Could you offer some more clarification?

**Comment by bessonette** [comment]
I actually went about it a slightly different way. In my app delegate I do this when re-establishing the session. The keychain values here are initially set after success in [DIOSUser userLoginWithUsername].

```
NSString *sessionName = [keychain objectForKey:(__bridge id)kSecAttrAccount];
NSString *sessionValue = [keychain objectForKey:(__bridge id)kSecValueData];
NSString *tokenValue = [keychainToken objectForKey:(__bridge id)kSecValueData];

DIOSSession *session = [DIOSSession sharedSession];
[session addHeaderValue:[NSString stringWithFormat:@"%@=%@", sessionName, sessionValue] forKey:@"cookie"];
[session addHeaderValue:[NSString stringWithFormat:@"%@", tokenValue] forKey:@"X-CSRF-Token"];

[DIOSSystem systemConnectwithSuccess: ^(AFHTTPRequestOperation *operation, id responseObject) {
            NSLog(@"SUCCESS RECONNECT");
        } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
            NSLog(@"FAIL RECONNECT: %@", error);
        }
```

**Comment by schlank** [comment]
Thanks guys, this solved it for me.  Thanks for the detailed code example @bessonette
