### ISSUE TITLE
Creating Field Collections

### ISSUE THREAD

**Issue by edouardgab** [kylebrowning/drupal-ios-sdk#108]
Hi everyone,

I am trying to find a way to create Field Collections. I am having some hard time with this.

I have activated "Services Entity" (https://www.drupal.org/project/services_entity), Tried a few different codes, but can't manage to do anything.

If anyone has an idea, it would be great! Thanks a lot.

Here is what I have tried (uid is a unique number generated by content on the app, and field_products_sale is the field collection name):

```
    NSMutableDictionary *entityData = [NSMutableDictionary new];
    [entityData setObject:uid forKey:@"uid"];
    [entityData setObject:@"field_collection_item" forKey:@"type"];
    [entityData setObject:[NSString stringWithFormat:@"%d",lastTitleInt] forKey:@"host_entity"];

    NSDictionary *productName = [NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:[NSString stringWithFormat:@"%@",order.product], nil] forKeys:[NSArray arrayWithObjects:@"value", nil]];
    NSDictionary *productNameLanguageDict = [NSDictionary dictionaryWithObject:[NSArray arrayWithObject:productName] forKey:@"und"];
    [entityData setObject:productNameLanguageDict forKey:@"field_product_text_ref"];


    [DIOSEntity entitySave:entityData name:@"field_products_sale" success:^(AFHTTPRequestOperation *op, id response) { } failure:^(AFHTTPRequestOperation *op, NSError *err) {  }
     ];
```

**Comment by kylebrowning** [comment]
Hrmm, I just tested this in Drupal 8 , tho I don't think Im going to go back to working on 7.x anytime soon, if anyone wants to open this up with a PR I'm happy to help.
