### ISSUE TITLE
Different responseObjects for DIOSSystem systemConnectwithSuccess: and DIOSUser userLogin:

### ISSUE THREAD

**Issue by andrewjlow** [kylebrowning/drupal-ios-sdk#109]
Hi there,
I use <strong>DIOSUser userLogin: success: failure:</strong> to login to my app and server.

To check whether the session is still valid, I use <strong>DIOSSystem systemConnectwithSuccess: failure:</strong>

If I login as the administrator the session check works - the responseObject for each are for the same session.

However if I log in as just an authenticated user- not the administrator with no roles-  the session check does not work. The responseObject I get back in the call <strong>DIOSSystem systemConnectwithSuccess: failure:</strong> is for an anonymous user session and the session id is totally different to the responseObject I got back for the userLogin.

Would anyone know what the problem is or what I am doing wrong?
Please let me know if any additional information is required from me.
Thank you!

**Comment by kylebrowning** [comment]
Set your NSURLCache to 0

```
    NSURLCache *sharedCache = [[NSURLCache alloc] initWithMemoryCapacity:0
                                                            diskCapacity:0
                                                                diskPath:nil];
    [NSURLCache setSharedURLCache:sharedCache];
```
