### ISSUE TITLE
CSRF token issues

### ISSUE THREAD

**Issue by Trexology** [kylebrowning/drupal-ios-sdk#110]
Somehow when calling [DIOSSystem systemConnectwithSuccess] apparently does not return a "token" value.

Therefore [[DIOSSession sharedSession] setCsrfToken:[responseObject objectForKey:@"token"]];
is always null causing a 'CSRF validation failed' 

Currently turning back to the older solution of storing the CSRFToken in NSUserDefault after successful login
[_userDefaults setObject:[response objectForKey:@"session_name"] forKey:@"cookiename"];
[_userDefaults setObject:[response objectForKey:@"sessid"] forKey:@"cookievalue"];
[_userDefaults setObject:[response objectForKey:@"token"] forKey:@"CSRF-Token"];

and setting it manually every time the app loads

 NSString *sessionName = [_userDefaults objectForKey:@"cookiename"];
 NSString *sessionValue = [_userDefaults objectForKey:@"cookievalue"];
 NSString *tokenValue = [_userDefaults objectForKey:@"CSRF-Token"];

[_session addHeaderValue:[NSString stringWithFormat:@"%@=%@", sessionName, sessionValue] forKey:@"cookie"];
 [_session addHeaderValue:[NSString stringWithFormat:@"%@", tokenValue] forKey:@"X-CSRF-Token"];

*Using Drupal 7 with drupal-ios-sdk 2.1.2

**Comment by kylebrowning** [comment]
Im currently not working on the 2.x branch. If someone wants to reopen this issue with a PR request let me know.
