### ISSUE TITLE
Does DIOS work with Swift?

### ISSUE THREAD

**Issue by ocramk** [kylebrowning/drupal-ios-sdk#111]
Hi there :)

I'm new the ios-dev and wanted to use DIOS with swift. So far I installed DIOS 2.0 by pod successfully. Everything get compiled fine but I never got it working to communicate with drupal :(

Here are some snippets I already tried: 

//> 1. SESSION > seems to call drupal service endpoint by oAuth 
var sharedSession: DIOSSession = DIOSSession.sharedSession()
sharedSession.baseURL = NSURL.URLWithString("http://xxx.xx")
// sharedSession.baseURL  has no setBasicAuthCredsWithUsername method :(
DIOSSession.setupDios()

//> 2. USER LOGIN > missing method
var user: DIOSUser = DIOSUser()
// user has no login method :(

//> 3. USER GET > callbacks get never hooked
DIOSUser.userGet(uid,
            success:{
                (AFHTTPRequestOperation op, AnyObject response) in
                println("success")
            },
            failure:{
                (AFHTTPRequestOperation op, AnyObject response) in
                println("failure")
            }
)

Can anybody tell me how to get it working? Currently I setup facebook sdk for ios on my swift app. That's working. My plan is to take the uid from facebook and auth. it agains my user profile fields. If available an auth would be grant. Otherwise I would insert new user with facebook fields (name, email) and uid. 
If a facebook login isn't available at this user I would need an fallback with registration and login by name and password.

thx for help!
ocramk

**Comment by kylebrowning** [comment]
It works but you need to include the `-OBJc` compiler variable.
