### ISSUE TITLE
viewGet request never times out, causes success and failure blocks to never be called.

### ISSUE THREAD

**Issue by jeremywhuff** [kylebrowning/drupal-ios-sdk#122]
I am calling viewGet:success:failure, and the success/failure blocks are never called. I can see some of what's going on, and I think it's an issue within DIOSSession.

When viewGet:success:failure calls sendRequestWithPath:method:params:success:failure:, [self systemConnected] is NO for the DIOSSession object. Therefore, tryOperationAgainAfterSystemConnect: is scheduled on a timer (line 271 of DIOSSession.m).

When tryOperationAgainAfterSystemConnect: is called, [self systemConnected] is still NO, meaning that it will keep trying agin, and again, and again.

There should be a limit on the number of times this function can be called for a given timer, and when that limit is reached, the failure block is called with an appropriate error.

**Comment by kylebrowning** [comment]
Interesting. I like the sound of this, Im wondering why its not timing out though :-1:

**Comment by jeremywhuff** [comment]
I'm finding some other possibly related issues. Not sure if I should create another issues or keep all of the discussion here.

When I call systemConnectwithSuccess:success:failure, I also am not getting any success or failure blocks called. Looking at that function, it's pretty clear that the failure block is not used anywhere. I would expect it to be called on line 60, in getCSRFTokenWithSuccess:failure.

So it seems to not be succeeding on the CSRF token, but I haven't dug in too much yet. After it doesn't succeed there, the session's systemConnected is forever set to NO, which causes these infinite timer loops that I mentioned before.

I'm using V2.1.5 of the SDK, by the way.

**Comment by jeremywhuff** [comment]
Both of the issues I've stated here are fixed in my pull request.
