### ISSUE TITLE
Empty CSRF token causes crash (branch 2.x)

### ISSUE THREAD

**Issue by jeremywhuff** [kylebrowning/drupal-ios-sdk#126]
I'm getting a crash on line 210 of DIOSSession.m. It's because the call to get the CSRF token is succeeding, but the responseObject has no data. Thus, [responseObject bytes] returns nil, and stringWithUTF8String: crashes.

I was looking at fixing this in two different ways. Which one makes sense?

1) Run a check on responseObject, and if data is empty, set aCsrfToken to nil, or perhaps @"".

2) Run a check on responseObject, and if data is empty, treat it as an error. This means don't set the CSRF token, create an NSError, and call the failure block.

**Comment by kylebrowning** [comment]
I like option 2.

You should always get a CSRF token back. Any idea why you are not?

**Comment by jeremywhuff** [comment]
Any preference on structure of an NSError (domain, code, userInfo)?

At this point, I have no idea why I'm getting empty CSRF tokens. I've had a lot of issues with getting a bunch of CSRF token errors if a user hasn't used the app for a week, then tries to run it. It's as though the CSRF token session has expired.

I don't know much about CSRF tokens, and I'm not a Drupal developer, so sorry if this doesn't make 100% sense ;)
