### ISSUE TITLE
Feature request: Process images

### ISSUE THREAD

**Issue by kevcol** [kylebrowning/drupal-ios-sdk#149]
It would be great if waterwheel processed images.

**Comment by kylebrowning** [comment]
Ive updated the demo to include showing downloading the image.

However this only works with Drupal 8.3 so if you are using BLT/Composer, you can add

```
            "drupal/core": {
              "Image URL formatter" : "https://www.drupal.org/files/issues/2517030-125.patch"
            }
```

And enable Response Image module.
