### ISSUE TITLE
Feature request: Process audio files

### ISSUE THREAD

**Issue by kevcol** [kylebrowning/drupal-ios-sdk#150]
It would be great if waterwheel processed audio files.  

I assume this could be similar to processing images, so, Kyle, if you do add photo support and point me toward the code that handles that, I'd be happy to take a shot at adding audio support

**Comment by kylebrowning** [comment]
I do believe Audio files are support. Are you saying if Waterwheel received an audio file that it converted it to a iOS SDK Audio Class?

@kevcol ^

**Comment by kylebrowning** [comment]
Closing, as I havnt heard much on this. 

Re-open if you seem necessary!
