### ISSUE TITLE
Update to swift 5.0

### ISSUE THREAD

**Issue by kylebrowning** [kylebrowning/drupal-ios-sdk#161]
- [ ] Cleanup static method calls
- [ ] Use new `Result` type

**Comment by andrewjlow** [comment]
FYI - It seems ObjectMapper was written with Swift 3.2. Swift 3.2 is not supported anymore in Swift 5.0:

![image](https://user-images.githubusercontent.com/5027396/58226333-9b2d8300-7d69-11e9-927f-bcc0343c085c.png)

**Comment by kylebrowning** [comment]
I’ve got a new branch that basically is a rewrite with swift 5 and Codable. 

Very soon.

**Comment by kylebrowning** [comment]
I don’t want to leave anyone hanging / waiting. 

Working on 5.0 still. Almost there

**Comment by kylebrowning** [comment]
Update here. Should be ready this weekend.

**Comment by Yanyi1135** [comment]
Very appreciate for the update!

**Comment by alexrubin** [comment]
@kylebrowning were you ever able to finish up the updates for Swift 5?

**Comment by brittanyblair** [comment]
Hey @kylebrowning did you ever end up posting the fix for Swift 5 somewhere? :D

**Comment by kylebrowning** [comment]
hey @brittanyblair long time, no I havn't gotten around to finishing it. Im not sure I will given my time these days.

For anyone else tumbling across this Im happy to turn the project over. 

My hope is one day I can return to work on it, but given the climate right now, Im focused on other things.

Wish I had better news.

**Comment by brittanyblair** [comment]
> hey @brittanyblair long time, no I havn't gotten around to finishing it. Im not sure I will given my time these days.
> 
> For anyone else tumbling across this Im happy to turn the project over.
> 
> My hope is one day I can return to work on it, but given the climate right now, Im focused on other things.
> 
> Wish I had better news.

All good! Came across the Swift 5 error and was curious. And long time indeed! Hope you're well :)
