### ISSUE TITLE
DIOSconnect error 

### ISSUE THREAD

**Issue by bamlhs** [kylebrowning/drupal-ios-sdk#18]
Hello,

thanks for Dios it's realy nice work. 

I'm using:

Services    6.x-2.4
DIOS 6.x-2.x

in after logout session will be null and if user login again program will crash cuz session is null 

error in DIOSConnect.m line 197

```
        [self setSessid:[[plist objectForKey:@"#data"] objectForKey:@"sessid"]];
        [self setUserInfo:[[plist objectForKey:@"#data"]objectForKey:@"user"]];
```

my logout function is: 

```
   DIOSUser *user = [[DIOSUser alloc] initWithSession:[delegate session]];
    [user logout];

    if ([[user connResult] objectForKey:@"#data"]) {
        [delegate setSession:user];
    }

    NSLog(@"logout: data %@",[[user connResult] objectForKey:@"#data"]);

 [user release];
```

the output for nslog is 
2011-07-28 12:27:12.443 sorti[5327:b303] logout: data 1

thanks

**Comment by bamlhs** [comment]
When I init session again in logout it's work fine 

I added this in my logout function 

 delegate.session = [[DIOSConnect alloc] init];

**Comment by kylebrowning** [comment]
Yeah, Services 2.4 is not consistent with its returns, user.logout will return just a a TRUE value which PHP changes to a 1 for string :(

Id suggest using 3.x because its a lot more stable.
