### ISSUE TITLE
Authenticated calls

### ISSUE THREAD

**Issue by ghost** [kylebrowning/drupal-ios-sdk#22]
Hello,

Sorry if this is not the proper place to put this question,..

I've started using this library. Want to thank you for your amazing job in this project.

I have all nodes of my Drupal 7 accessible only to authenticated users. I'm able to connect and login using this sdk but I can't get the nodes because of an authentication issue.

I wonder if someone could help me with this pseudo-code so I can get nodes from my drupal installation via authenticated calls.

DiosConnect \* session = [[DiosConnect alloc] init];

DiosUser \* user = [[DiosUser alloc] initWithSession:session];

id response = [user loginWithUsername:@"admin" andPassword:@"myPassword"];

// I get a good response here

DiosNode \* nodeController = [[DiosNode alloc] initWithSession:session];

id nodesList = [nodeController nodeGetIndex];

// I get a null list of nodes and an Authentication needed log message

Thanks very much!!

Jordi

**Comment by kylebrowning** [comment]
This is currently an issue with services.

http://drupal.org/node/1240074

Try the patch there.

**Comment by ghost** [comment]
Thanks Kyle,

I actually found what was happening, I did not activate the "Session Authentication" of the services end point I created in Drupal.

Anyway, big thanks for the project!

J

**Comment by kylebrowning** [comment]
JordiOS no problem, thanks for using it!
