### ISSUE TITLE
drupal 7.9 + services 3 fails

### ISSUE THREAD

**Issue by mpycio** [kylebrowning/drupal-ios-sdk#23]
Add node doesn't work with above setup, seems that array(0 => array('method' => ..., 'sessid' => ..., 'node' => ...)) is incorrect.
Node must be the only key or whole structure must be flattened. Check services.runtime.inc lines 368 & 393.

To make it work I had to change runMethod by removing other 2 params :

line 149:

```
// this breaks drupal7+services3, also need to remove method param. Node must be only param sent
//[self removeParam:@"sessid"];
//[self addParam:[self sessid] forKey:@"sessid"];
[self removeParam:@"method"];
```

Thx for this lib, good work!
M

**Comment by kylebrowning** [comment]
Can you try the HEAD of drupal-ios-sdk?

**Comment by kylebrowning** [comment]
Closing as this issue is fixed in HEAD
