### ISSUE TITLE
Cannot create user programmatically on Drupal 7

### ISSUE THREAD

**Issue by chewedon** [kylebrowning/drupal-ios-sdk#25]
Using code like:

NSMutableDictionary *newUser = [[NSMutableDictionary alloc] init];
[newUser setObject:@"DrupalUser" forKey:@"name"];
[newUser setObject:@"somepassword" forKey:@"pass"];
[newUser setObject:@"drupaluser@email.com" forKey:@"init"];
[newUser setObject:@"drupaluser@email.com" forKey:@"mail"];
[newUser setObject:@"1" forKey:@"status"];

[user userSave:newUser];

It says HTTP/1.0 406 Not Acceptable: Username field is required. E-mail address is required. Password field is required.

Using the same forKey values as the above code in PHP code works so I am confident the forKey values are correct.

**Comment by kylebrowning** [comment]
Can you try this with the new ay of doing things. 7.x-3.x was a bit wonky at times :(
