### ISSUE TITLE
User.save function in Drupal IOS SDK does not save user picture 

### ISSUE THREAD

**Issue by sudhanwa** [kylebrowning/drupal-ios-sdk#28]
When saving user picture using the userSave method, the method returns success, but the picture field is not updated. No warnings appear in the services diagnostic logs.

I am trying to pass the uploaded picture's URL to the picture field (complete path, relative path) , but no luck. 
Email ID field updates are reflected correctly.

Saw a similar post on drupal.org - http://groups.drupal.org/node/124584#comment-733769 
Seems like an old post, but no solution as yet.

The parameters passed in are seen in the drupal logs as follows -

```
[0] => 13872
```

    [1] => Array
        (
            [method] => user.save
            [data] => Array
                (
                    [name] => username
                    [picture] => http://mydrupalsite/sites/default/files/user_profiles/picture-13872.jpg
                    [uid] => 13872
                    [mail] => myemail@mail.com
                )

            [sessid] => hk951sjiq22ibf1iu1dt71rsu0
            [uid] => 13872
        )

Drupal Version 6.22
DIOS Ver  - MPL 1.1/GPL 2.0

Any help is truly appreciated.

**Comment by drewish** [comment]
You try uploading the file separately and then specifying an fid?

**Comment by kylebrowning** [comment]
It needs to be an FID, not a link to the file.
