### ISSUE TITLE
views don't accept contextual filters

### ISSUE THREAD

**Issue by kev52** [kylebrowning/drupal-ios-sdk#29]
Hi,

is it possible to add contextual filters to a views call? I tried this:

DIOSView *stationsView = [[DIOSView alloc] init];
            NSMutableDictionary *stationsParams = [NSMutableDictionary new];

```
        [stationsParams setValue:@"stations" forKey:@"view_name"];
        NSString *nid = [theGuide.details.data valueForKey:@"nid"];
        [stationsParams setObject:[NSArray arrayWithObject:nid] forKey:@"args"];
        [stationsParams setValue:@"default" forKey:@"display_id"];

        [stationsView viewGet:stationsParams success:^(AFHTTPRequestOperation *operation, id responseObject) { 
```

but it doesn't work! Is there any solution?

**Comment by meSte** [comment]
I ended up using exposed filters instead of contextual filters. Maybe this can work also for you.
Try looking here https://github.com/workhabitinc/drupal-ios-sdk/pull/32 , DIOSView now can handle whatever exposed filter you have in your view.

**Comment by estock** [comment]
Sorry, I'm confused, IS there support for contextual filters, or is this a feature request. If so how would I add  a viewParam the passed a contextual filter?

**Comment by kylebrowning** [comment]
I think this a feature request for services _views, not Drupal ioS SDK
