### ISSUE TITLE
Blocking Operation

### ISSUE THREAD

**Issue by MrMaksimize** [kylebrowning/drupal-ios-sdk#38]
Hi Guys,

First off great job, this seems really cohesive and much nicer than the previous one based on ASI.

Had a question though.. Seems like the request callbacks tend to spin off into different threads.  But what if I want to issue a request that I want to wait to finish until executing the next steps?

Thanks again!

**Comment by kylebrowning** [comment]
Theres two things you can do.
1. Spawn a timer that checks for a value every so many seconds. 
2. If you need real time. Just use NSNotificationCenter to send a notification when that process is done, and have another object register against that notification name. More on that [here](https://developer.apple.com/library/mac/#documentation/Cocoa/Reference/Foundation/Classes/nsnotificationcenter_Class/Reference/Reference.html).

**Comment by MrMaksimize** [comment]
Great!! The nsnotification works awesome!! I ended up doing that this weekend without fully realizing that I was making it synchronous ;)
