### ISSUE TITLE
Adding file to a node?

### ISSUE THREAD

**Issue by thomasbk** [kylebrowning/drupal-ios-sdk#4]
Hi Kyle,

I haven't been able to figure out how to add a file to a node via node.save. We have added an image field (type file) and a credit field (type text) to a node, and I can't figure out how to edit them with the drupal-ios-sdk.

I don't think there is an example of this in the example app. I've seen some examples online using php with arrays, but it doesn't seem to work on iOS.

Do you have an example of adding the uploaded file (in the example app) to a node?

Thanks!
Thomas B.

**Comment by kylebrowning** [comment]
Hey Thomas, let me whip up an example for you and ill add it to the example app.
Once its done I will commit it, and then post here.

**Comment by thomasbk** [comment]
Great! Thanks for your time!

**Comment by kylebrowning** [comment]
OK the example app now shows how you can accomplish this.
http://github.com/workhabitinc/drupal-ios-sdk-example

**Comment by thomasbk** [comment]
It works! 
You're great! Thanks for all your help!

**Comment by kylebrowning** [comment]
Glad I could help!
