### ISSUE TITLE
Why use instance methods instead of class methods?

### ISSUE THREAD

**Issue by drewish** [kylebrowning/drupal-ios-sdk#41]
I'm curious about the choice of implementing all the methods on say DIOSUser as instance methods rather than class methods, especially since the instances have no properties. In PHP I guess I'd be asking why you didn't make these static functions.

To login you need to initialize an unnecessary object:

```
 DIOSUser *user  = [[DIOSUser alloc] init];
```

Before you can call the method:

```
[user userLoginWithUsername:name andPassword:pass ... ];
```

But then you ought to be calling release when you're done with it:

```
[user release];
```

But if these were class methods you could just do:

```
[DIOSUser userLoginWithUsername:name andPassword:pass ...];
```

And in that case you could remove the redundant "user" prefix from the method name... which might be okay since this would break backwards compatibility.

**Comment by kylebrowning** [comment]
Merged in, thank you for this. Ive been wanting to do it for a bit.
