### ISSUE TITLE
Logout errors

### ISSUE THREAD

**Issue by drewish** [kylebrowning/drupal-ios-sdk#43]
When logging out using I'm getting 

```
Error Domain=NSCocoaErrorDomain Code=3840 "The operation couldn’t be completed. (Cocoa error 3840.)" (JSON text did not start with array or object and option to allow fragments not set.) UserInfo=0x68855a0 {NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}
```

So it looks like services (7.x-3.1) is returning 'null' for http://localhost/api/user/logout which is strange because the code looks like it should be returning 'true'. I wonder if it's pointed at the _user_resource_retrieve callback... I'm not sure if this should be a DIOS bug or services bug yet. It's not logging me out so I'm guessing it's not getting called properly rather than an output issue.

**Comment by drewish** [comment]
Updated to 7.x-3.x-dev and it actually logs me out and returns true... which ironically gives the same error. So the fix is either modifying services to return the result in an array or modifying AFNetworking/AFJSONUtilities.m to change line 203 from:

```
    NSUInteger readOptions = 0;
```

To

```
    NSUInteger readOptions = NSJSONReadingAllowFragments;
```

I'll look at opening an issue in that library too.

**Comment by drewish** [comment]
I've submitted a pull request to AFNetworking: https://github.com/AFNetworking/AFNetworking/pull/374

**Comment by kylebrowning** [comment]
This is interesting thanks for bringing up this issue. unfortunately we cant change Services code just yet because it might break clients. Im working on code that will fix this here. http://drupal.org/node/1436366

**Comment by kylebrowning** [comment]
This is fixed int he latest dev release.
