### ISSUE TITLE
nodeAttachFile example for Services 7.x-3.x

### ISSUE THREAD

**Issue by c5f** [kylebrowning/drupal-ios-sdk#46]
Hi Kyle,

It looks like file_attach is still a work in progress on Services 7.x-3.x: http://drupal.org/node/1484992

I'm wondering if there's a DIOS 2.0 example out with working file attachment.

I am unable to attach files from DIOS at the moment, and I don't know if my issue is my Drupal configuration or DIOS.

**Comment by JC2011** [comment]
I'm trying to attach file to a node and it doesn't work.
The data was sent and i received an error :
Error Domain=com.alamofire.networking.error Code=-1011 "Expected status code in (200-299), got 404" UserInfo=0x73290a0 {NSErrorFailingURLKey=http://mysite/api/node/84/attach_file?field_name=field_photo, NSLocalizedDescription=Expected status code in (200-299), got 404}

Is the nodeAttachFile method work ?

I'm working on 7.14 drupal version .

Thanks in advance

**Comment by kylebrowning** [comment]
Does this code help you?

``` obj-c
  [[AppDelegate customStatusBar] showWithStatusMessage:@"Uploading"];
  NSData *imgData = UIImageJPEGRepresentation(img, 1.0);

  NSMutableDictionary *file = [[NSMutableDictionary alloc] init];
  NSString *base64Image = [(NSData *)imgData base64EncodedString];
  [file setObject:base64Image forKey:@"file"];
    NSString *timestamp = [NSString stringWithFormat:@"%d", (int)[[NSDate date] timeIntervalSince1970]];
  NSString *imageTitle = [[articleTitle text] stringByReplacingOccurrencesOfString:@" " withString:@"_"];
  NSString *filePath = [NSString stringWithFormat:@"%@%@.jpg",@"public://", imageTitle];
  NSString *fileName = [NSString stringWithFormat:@"%@.jpg", imageTitle];
  [file setObject:filePath forKey:@"filepath"];
  [file setObject:fileName forKey:@"filename"];
  [file setObject:timestamp forKey:@"timestamp"];
  NSString *fileSize = [NSString stringWithFormat:@"%d", [imgData length]];
  [file setObject:fileSize forKey:@"filesize"];
  [DIOSFile fileSave:file success:^(AFHTTPRequestOperation *operation, id responseObject) {
    [file setObject:[responseObject objectForKey:@"fid"] forKey:@"fid"];
    [file removeObjectForKey:@"file"];
    [self setFileData:file];
    [[AppDelegate customStatusBar] hide];
  } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
    #warning We should let the user know rather than dumping a log
    NSLog(@"Something went wrong: %@", [error localizedDescription]);
  }];
  [self dismissModalViewControllerAnimated:YES];
```

**Comment by JC2011** [comment]
Thanks but how to link the file with a node on site ???

Best regards,

Envoyé de mon iPhone

**Comment by JC2011** [comment]
I found the solution.
After saving file, I set my field_photo of my node with the fid.

**Comment by loh-xx** [comment]
Hi JC2011,
Can you tell me how you set node field_photo with the fid.
Thank

**Comment by loh-xx** [comment]
Thank you, I did it.

**Comment by karschsp** [comment]
@loh Care to explain how?

**Comment by karschsp** [comment]
Well, I eventually figured it out.  I'm sure it's wrong, because I don't really know what I'm doing, but it works.  Anyway, after uploading the file, grab the fid and start creating a new node like so...

<pre>
NSMutableDictionary *newNodeData = [NSMutableDictionary new];
[newNodeData setValue:fldTitle.text forKey:@"title"];
[newNodeData setValue:@"photo" forKey:@"type"];
[newNodeData setValue:@"und" forKey:@"language"];
</pre>

These next four lines are where you add the file (in my case, the field is field_photo)...

<pre>
NSMutableDictionary *dict = [NSMutableDictionary dictionary];
[dict setObject:[NSString stringWithFormat:@"%@", fid] forKey:@"fid"];
NSDictionary *fidLangDict = [NSDictionary dictionaryWithObject:[NSArray arrayWithObject:dict] forKey:@"und"];
[newNodeData setObject:fidLangDict forKey:@"field_photo"];
</pre>

Then finish up...

<pre>
[DIOSNode nodeSave:newNodeData success:^(AFHTTPRequestOperation *operation, id responseObject) {
    //Successful node Creation, etc, etc
</pre>

Suggestions welcome!

**Comment by brittanyblair** [comment]
Hey @karschsp - 

Your code = super helpful. Implemented the above, and the image uploads to my server just fine. However no matter what I seem to do, the image won't attach to the corresponding node. The name of my image field is "field_photo". Am I missing something? Here's my code:
```
- (IBAction)saveButton:(id)sender {
    
    NSMutableDictionary *nodeData = [NSMutableDictionary new];
    [nodeData setValue:_itemName.text forKey:@"title"];

    NSData *imgData = UIImageJPEGRepresentation(self.imageView.image, 0.5);
    
    NSMutableDictionary *file = [[NSMutableDictionary alloc] init];
    NSString *base64Image = [imgData base64EncodedString];
    [file setObject:base64Image forKey:@"file"];
    NSString *timestamp = [NSString stringWithFormat:@"%d", (int)[[NSDate date] timeIntervalSince1970]];
    NSString *imageTitle = _itemName.text;
    NSString *filePath = [NSString stringWithFormat:@"%@%@.jpg",@"public://stored/", imageTitle];
    NSString *fileName = [NSString stringWithFormat:@"%@.jpg", imageTitle];
    [file setObject:filePath forKey:@"filepath"];
    [file setObject:fileName forKey:@"filename"];
    [file setObject:timestamp forKey:@"timestamp"];
    NSString *fileSize = [NSString stringWithFormat:@"%lu", (unsigned long)[imgData length]];
    [file setObject:fileSize forKey:@"filesize"];
    
    [DIOSFile fileSave:file success:^(AFHTTPRequestOperation *operation, id responseObject) {
        NSLog(@"File Saved!");
        
      [file setObject:[responseObject objectForKey:@"fid"] forKey:@"fid"];
      [file removeObjectForKey:@"file"];
        
    } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
        NSLog(@"Failed to save file!");
    }];
    
    NSDictionary *bodyValues = [NSDictionary dictionaryWithObjects:[NSArray arrayWithObjects:_itemDescrip.text, nil] forKeys:[NSArray arrayWithObjects:@"value", nil]];
    NSDictionary *languageDict = [NSDictionary dictionaryWithObject:[NSArray arrayWithObject:bodyValues] forKey:@"und"];
    [nodeData setObject:languageDict forKey:@"body"];

    NSDictionary *fidLangDict = [NSDictionary dictionaryWithObject:@[file] forKey:@"und"];
   [nodeData setObject:fidLangDict forKey:@"field_photo"];
   NSLog(@"%@", fidLangDict);
    
    [nodeData setObject:@"storage_item" forKey:@"type"];
    [nodeData setObject:@"und" forKey:@"language"];

    [DIOSNode nodeSave:nodeData success:^(AFHTTPRequestOperation *operation, id responseObject) {
        NSLog(@"Item successfully added to Database!");
      
    } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
        NSLog(@"Failed to add item to database!");
    }];
```
