### ISSUE TITLE
No JSON parsing functionality available

### ISSUE THREAD

**Issue by kev52** [kylebrowning/drupal-ios-sdk#47]
Hi,

on some devices an error like 
"NSInternalInconsistencyException: No JSON parsing functionality available
Msg: Crash!" 

produces a crash. I don't know why this happens or what I can do to stop this.

Any ideas?

**Comment by kylebrowning** [comment]
I dont really have any ideas, I havnt seen this error, if you can find a way to reproduce let me know.
