### ISSUE TITLE
Logout error ?

### ISSUE THREAD

**Issue by JC2011** [kylebrowning/drupal-ios-sdk#48]
I'l trying to use log out function with the last drupal iOS sdk library and i received this error :

Error Domain=JKErrorDomain Code=-1 "Unexpected token, wanted '{', '}', '[', ']', ',', ':', 'true', 'false', 'null', '"STRING"', 'NUMBER'." UserInfo=0x30dde0 {JKAtIndexKey=0, JKLineNumberKey=1, NSLocalizedDescription=Unexpected token, wanted '{', '}', '[', ']', ',', ':', 'true', 'false', 'null', '"STRING"', 'NUMBER'.}

How to resolve it ?

Thanks

**Comment by JC2011** [comment]
Apparently, the logout works but i always receive this error from AFNetworking.
How to resolve it ???

**Comment by JC2011** [comment]
In fact, i resolve it. My Rest API Services wasn't the last version.
Sorry

**Comment by utneon** [comment]
Update to services 7.x-3.2 and the issue goes away.
