### ISSUE TITLE
Download Drupal 7 private file

### ISSUE THREAD

**Issue by loh-xx** [kylebrowning/drupal-ios-sdk#52]
Hi,

Please can somebody tell me how to download Drupal 7 private file with in Objective C?

I can only download public file with NSURLConnection.
Also I implement hook_file_download and I can download private file in browser but I can't download it in Objective C.

Thank

**Comment by kylebrowning** [comment]
Its not possible to downloading a private file, thats why its private.

**Comment by loh-xx** [comment]
Thank you Kyle for your answer, But the file is mine (author) and I have permission to do everything with it.

**Comment by loh-xx** [comment]
It works for me now.
Thank
