### ISSUE TITLE
Error 406 when Session Authentication enabled

### ISSUE THREAD

**Issue by Yiphi** [kylebrowning/drupal-ios-sdk#53]
Hello.

First, thank you for the tremendous work that you put into building and developing Drupal-iOS-SDK.  It is an amazing piece of work and I am impressed by its power daily.

Second, as a bit of background, I am writing an iOS app that allows users to login to my Drupal site with their iPhone/iPad and access their inputted data currently stored/displayed in Views.

Now, to my question/problem.  So far, I have been able to successfully login to my Drupal site with the iOS app with OAuth and Session Authentication switched to off.  However, as soon as I enable  Session Authentication, I get a 406 error.  I have tried looking online for a solution but, unfortunately, I have been unable to do so.  What could be causing this problem and how would you recommend that I go about trying to resolve it?

On a similar note, my hypothesis is that disabling Session Authentication is what is causing me to get a 401 error when trying to get the app to display the views I've created.  Could that be the case?  Will resolving my issue above so that I can enable Session Authentication then allow me to access the views?

Thank you in advance for your help and have a great day!

Sincerely,

doctorDrupal

**Comment by Yiphi** [comment]
Okay--I think I'm making some progress.  For the time being, I've disabled Session Authentication and don't have to deal with the 406 error.  Additionally, I adjusted my Drupal views settings and now am no longer getting a 401 error when using DIOSView's viewGet.  However, the responseObject for viewGet is a blank set that contains no view information. As a test, I implemented nodeGet that retrieves the node my view is linked to.  I then ran the app and observed that the information returned in nodeGet's responseObject doesn't match the information for the user that successfully logged in.  This makes me think that the session and/or user information is not getting passed from the app's first view (login view) to the app's second view (view that implements viewGet).

Can anybody help?  I know the Drupal community, and Drupal-iOS-SDK community, is quite large and active.  As such, I'm hopeful that someone can provide me with some insights and point me in the right direction.

Thanks in advance!

**Comment by kylebrowning** [comment]
Im not sure I entirely follow.

Which authenticaiton method are you using? oAuth?

406 erros usually mean the data you are sending is wrong.

401 means you are not authentication for that resource.

Can you be more specific in what you are sending vs what your receiving, maybe even post your endpoint.

**Comment by Yiphi** [comment]
Thank you for the prompt reply, Kyle.

I was only using Session Authentication.  And, after doing some more
research, it appears you are correct and the data I was sending was wrong.
 It looks like I need to be sending a cookie with headers that contain the
session info.  As such, I've disabled Session Authentication for the time
being so the app can login to my Drupal site.  The 406 error no longer
occurs after disabling Session Authentication.

The 401 error went away after I adjusted some settings on my view.

So, I think I'm making some progress.  My app is able to login and viewGet
successfully runs.  However, the responseObject for viewGet returns a blank
set that contains no Drupal views information. As a test, I also
implemented nodeGet that successfully runs and retrieves the node my Drupal
views are linked to. Unfortunately, I observed that the information
returned in nodeGet's responseObject doesn't match the information for the
user that successfully logged in. This makes me think that the session
and/or user information is not getting passed from the app's first
viewcontroller (login) to the app's second viewcontroller (the
viewcontroller that implements viewGet and nodeGet).  Thus, I need help
trying to figure out how to make the app's second viewcontroller implement
viewGet such that it displays the Drupal views for the user who logged in
on the app's first viewcontroller.

Again, thank you so much for taking the time to respond to my questions and
help me.  I hope that my questions and explanations make sense.  Again, my
sincere thanks for your help, Kyle.

**Comment by kylebrowning** [comment]
Thats odd, you shouldnt have to set the user information at all. Once logged in your cookies shoudl exist in the device and session authentication will be complete.

What information is returned in your nodeGet response object that is relevant to a logged in user? It shouldnt be anything unless you have altered the node resource to do something different.

**Comment by Yiphi** [comment]
Hi Kyle--thanks for your help with this.

I'm still having the 406 error whenever session authentication is enabled.  So, for the time being, I'll leave it disabled and deal with it later.  That being said, it appears to be working because people who don't successfully login from within the app can't see anything.  Along those lines, people who do successfully login can only see data they authored.  However, since I'm still having the issue, I'd like to keep this open.  I'll just come back to it at a later date.

Of note, views are now working but I have a new hurdle (isn't that always the case!).  I've created a new issue (#56) that discusses my new questions with views.

Thanks again for all your help.

**Comment by kylebrowning** [comment]
Are you still seeing this now?

**Comment by kylebrowning** [comment]
With Services 3.2

**Comment by Yiphi** [comment]
Yes--I'm still getting the 406 error whenever session authentication is enabled (using Services 3.2).

**Comment by kylebrowning** [comment]
Can you find in watchdog what the error Drupal is having and why its returning 406?

**Comment by estock** [comment]
I have witnessed this behavior as well. The first time I login, everything works fine. The second time I try to login, I get a 406 error. I have to go back into Drupal and make sure the user is logged out. It's a little confusing, should I attempt to logout every time I login? or is there a way to determine If I am logged in before I attempt to?

**Comment by mvarie** [comment]
What is the response status message? Are you getting "HTTP/1.1 406 Not Acceptable: Already logged in as xxxxx" ? I am in a similar situation and it's a bit of a nuisance that a perfectly valid login/password gets rejected _even_ if the cookie user is the same, but I guess that's just the way Drupal works.

Certainly not ideal, but depending on your requirements, you might consider checking the response status message and act accordingly:

```
NSString *responseStatusMessage = userService.responseStatusMessage;
if ([responseStatusMessage rangeOfString:@"Already logged in"].location != NSNotFound) {
    // do something
}
```

.. or, although I don't know how effective this is in your specific situation, you might clear your cookies beforehand:

```
NSArray *cookies = [[NSHTTPCookieStorage sharedHTTPCookieStorage] cookiesForURL: networkServerAddress];
for (NSHTTPCookie *cookie in cookies) 
{
    [[NSHTTPCookieStorage sharedHTTPCookieStorage] deleteCookie:cookie];
}
```

**Comment by kylebrowning** [comment]
Standard Drupal behavior is to keep the user logged in and reject new logins unless that session has been lost or is no longer valid.

This is working as intended, you need to keep track of whether you are logged in or not, and that can easily be done by checking [[DIOSSession sharedSession] user];
