### ISSUE TITLE
It seems delegate nodeSaveDidFinish not works

### ISSUE THREAD

**Issue by loh-xx** [kylebrowning/drupal-ios-sdk#55]

**Comment by kylebrowning** [comment]
delegates are no longer used, go for the block based approached in the new Drupal iOS SDK.

**Comment by onepartscissors** [comment]
I see that you have updated the https://github.com/workhabitinc/drupal-ios-sdk/wiki/drupal-ios-sdk-2.0 page as well.

You sir, are a gentleman and a scholar.

**Comment by kylebrowning** [comment]
Not fully updated but getting there ! :P
