### ISSUE TITLE
No visible @interface for 'DIOSUser' declares the selector 'initwithDelegate:'

### ISSUE THREAD

**Issue by onepartscissors** [kylebrowning/drupal-ios-sdk#57]
Hi All

i have found and installed the right libraries of AFNetworking and DIOS-SDK that don't give me 'retain' and 'release' errors when building for iOS5 / iOS 6 (so one that works with ARC), and it's now compiling fine, however, when i try and use of of the example code from the documentation page, for example:

<code>
DIOSUser *user = [[DIOSUser alloc] initWithDelegate:self];
[user userLoginWithUsername:@"myusername" andPassword:@"mypassword"];
</code>

I get an error on the first line, which states:

No visible @interface for 'DIOSUser' declares the selector 'initwithDelegate:'

Any ideas what this is due to? I've been googling and it seems to come back to instance methods and class methods?

**Comment by kylebrowning** [comment]
Thats because the Drupal IOS SDK is no longer instantiated, its all block based.

Try this code

``` obj-c
  [DIOSUser userLoginWithUsername:@"username" andPassword:@"password" success:^(AFHTTPRequestOperation *operation, id responseObject) {
    //successful
  } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
    //failed
  }];
```

**Comment by onepartscissors** [comment]
Ah, thank you Kyle!

That explains it well. Thanks so much!
