### ISSUE TITLE
Error on 'nodeAttachFile' in DIOSNode.m

### ISSUE THREAD

**Issue by onepartscissors** [kylebrowning/drupal-ios-sdk#58]
Hi Kyle

OK, don't hate me!

I've attempted to install now with either the Master version, and the Dev version, and both are giving me certain errors, so i'm not sure which to use, and where i'm doing wrong?

So on the Master one, DIOSNode.m throws up an error telling me i'm missing "AFJSONUtilities.h".

That wasn't part of the master version of AFNetworking, so i found that the 'experimental-network-reachability-backgrounding-fix' branch of AFNetworking contained that file, so i added that one to my project instead.

OK, with that file no longer missing, after cleaning, i now get an error on DIOSNode.m, saying:

Incompatible block pointer types sending 'void (^)(NSInteger, NSInteger,NSInteger)' to parameter of type 'void (^)(NSUInteger, long long, long long)'

if i comment that out, i get a million ARC errors on the AFNetworking files. So, back to the Master branch of AFNetworking, and i comment out the #import "AFJSONUtilities.h" line in DIOSNode.m.

So if i go with the Master version of AFNetworking, and comment out these lines of 'nodeAttachFile' in DIOSNode.m:

//  [operation setUploadProgressBlock:^(NSInteger bytesWritten, NSInteger totalBytesWritten, NSInteger totalBytesExpectedToWrite) {
//    NSLog(@"Sent %d of %d bytes", totalBytesWritten, totalBytesExpectedToWrite);
//  }];

I compile no problem, for now - but all i'm doing is sending a login request. I fear if i try and interact with nodes, my commented out code above is going to come back to haunt me!

So, after all that background, this DIOSNode.m error below:

Incompatible block pointer types sending 'void (^)(NSInteger, NSInteger,NSInteger)' to parameter of type 'void (^)(NSUInteger, long long, long long)'

How serious is this, and is there a proper way to fix this, short of just commenting out the offending lines?

**Comment by kylebrowning** [comment]
If you use this piece of code does it work? 

AFHTTPRequestOperation *operation = [[AFHTTPRequestOperation alloc] initWithRequest:request];
[operation setUploadProgressBlock:^(NSUInteger bytesWritten, long long totalBytesWritten, long long totalBytesExpectedToWrite) {
NSLog(@"Sent %lld of %lld bytes", totalBytesWritten, totalBytesExpectedToWrite);
}];

**Comment by kylebrowning** [comment]
You should disable ARC for the Drupal iOS SDK Files.
http://stackoverflow.com/questions/6646052/how-can-i-disable-arc-for-a-single-file-in-a-project

**Comment by onepartscissors** [comment]
Yes, that piece of code builds successfully - and i've not disabled ARC on the DIOS files, thanks Kyle!

I'm going to go and read through the various functions now and compare the new and old ways of doing things, i need to understand the block based approach a bit better, as opposed to the delegates idea - once i have my head around that i think this will be smoother sailing!

Thanks again for the (speedy) replies!
