### ISSUE TITLE
Issue with system.connect on 6.x-3.x

### ISSUE THREAD

**Issue by JaseElder** [kylebrowning/drupal-ios-sdk#6]
Hi,
great project! I'm using it extensively at the moment.
I've just noticed what may be a bug.

In DIOSConnect.m, ll198-199 and ll 204-205 the plist is accessed for key=#data then key=sessid/user.

Certainly in the Services 3.0-beta2 module, the plist doesn't return with a #data element, so sessid and user are left blank.
I'm using Hugo Wetterberg's REST Server plist module, and not Kyle's/your Plist Server module - perhaps the one wraps the data in #data and the other doesn't?

**Comment by kylebrowning** [comment]
hrmm,I tested this and it seems to be working on my end, weird.

Services 3.x does NOT required my plist module so thats good that you are not using it.

I wonder though whats going on, it shouldnt have those data references in it.

If you change them, does it work?

**Comment by JaseElder** [comment]
yeah, all fixed by removing the #data objectForKey reference. Sorry, should have mentioned that.
Fixed code:
                    [self setSessid:[plist objectForKey:@"sessid"]];
                    [self setUserInfo:[plist objectForKey:@"user"]];

**Comment by kylebrowning** [comment]
Fixed
