### ISSUE TITLE
Latest version of AFNetworking removes AFJSONUtilities file.

### ISSUE THREAD

**Issue by markdorison** [kylebrowning/drupal-ios-sdk#60]
The latest version of AFNetworking seems to have been refactored and no longer includes AFJSONUtilities.h/m. DIOSNode.m attempts to import this file.

**Comment by markdorison** [comment]
This is in reference to the master branch. This should either be updated or documentation should be updated to point to a specific version of AFNetworking to be used.

**Comment by jamesnw** [comment]
What version of AFNetworking should we use?

**Comment by karschsp** [comment]
I've found you can just comment that #import line out and the project will build.

**Comment by nickgs** [comment]
Hey guys. The pull request in issue #82 corrects this problem.

**Comment by kylebrowning** [comment]
Its been fixed.
