### ISSUE TITLE
NodeSave worked... then didn't. Session i think is to blame

### ISSUE THREAD

**Issue by onepartscissors** [kylebrowning/drupal-ios-sdk#63]
Hey Kyle

I've been working with the DIOS SDK some more (thanks for all the help getting me started with it).

I've managed to get my app logging onto the drupal site no problem, i've been able to read a node ID, and i even had it creating a node. This was all without any Authentication though...

So when i checked the Session Authentication tickbox in the services endpoint, i can still log on, but i'm really having no joy creating a session on the click of one button, and then managing to hold on to that session when calling another method - i've tried the examples found in other similar issues in the queue, but no luck.

Can you shed any light on how to work with the Session command, so that we can log on with a session and then use that session to create nodes, etc? Because even once i've logged on - even if i put it all into one method call, it still registers the 'create node' call as anonymous in Drupal's logs.

**Comment by kylebrowning** [comment]
This might actually be a bug in services that is fixed in dev, have you tried the dev release?

**Comment by onepartscissors** [comment]
I suspected as much - let me try the DEV and see what happens there - i will report back.

Man, is it just me, or is AFNetworking really not great? I know this all relies on it, but i just can't help shaking the feeling that it's causing more than a few issues. Probably just a suspicion though!

**Comment by onepartscissors** [comment]
Kyle, I think my question is better framed thusly:

I can successfully create a session with DIOSSession, and even save that into a cookie and the keychain, all that, i can log in with DIOSUser userLoginWithUsername, but then, when i try to create a node, DIOSNode nodeSave, i can only get it to save if i allow anonymous users to create nodes, otherwise it fails. So, my question is, having created the session, and logged in, how can i then "use" that session and logged in user to create the node? I have 2 different 'functions' (apologies for the javascript lingo - are they methods in obj-c?) attached to 2 different buttons, one for login, and one for create node, but they just seem to be so isolated from each other.

I do realize this is probably a very rudimentary question, but i really can't wrap my head around it - the DIOSNode never allows me to specify a username or session, so how do i then use my logged in session to create nodes?

Thanks for all the feedback and advice.

**Comment by onepartscissors** [comment]
I've gotten this working - i will post the steps i took for the benefit of others. Thanks for a great library, Kyle
