### ISSUE TITLE
No visible @interface for 'DIOSSession' declares the selector 'setBaseURL:'

### ISSUE THREAD

**Issue by EdwardHinkle** [kylebrowning/drupal-ios-sdk#64]
Hi! I'm excited to use this in a project, however I ran into an issue.

I added AFNetworking and Drupal iOS SDK. I get the following error:

DIOSSession.m:60:4: No visible @interface for 'DIOSSession' declares the selector 'setBaseURL:'

**Comment by kylebrowning** [comment]
Because you initWithBaseURL, the url isnt allowed to change.

**Comment by EdwardHinkle** [comment]
I'm confused, because that line of code wasn't a line I added. That was in the Drupal iOS SDK code I downloaded from here.... should I just remove it?
