### ISSUE TITLE
Threaded comments.

### ISSUE THREAD

**Issue by JaseElder** [kylebrowning/drupal-ios-sdk#7]
I've noticed that created comments aren't threaded, and have modified my copy to fix this.
Can I submit a patch, or give details somewhere of the fix?

Cheers

**Comment by kylebrowning** [comment]
You can fork my repository and submit a pull request

**Comment by kylebrowning** [comment]
If you need help forking and getting used to github, you can reach me anytime on irc #drupal-services on irc.freenode.net

**Comment by JaseElder** [comment]
Cheers, I'll have a look at that tonight. Never used git, only svn/cvs so I'll probably see you on irc.

**Comment by kylebrowning** [comment]
Cool, must open a pull request whenever
