### ISSUE TITLE
Drupal iOS SDK question (not necessarily an error or problem)

### ISSUE THREAD

**Issue by Yiphi** [kylebrowning/drupal-ios-sdk#71]
Hello all.

First and foremost, Drupal iOS SDK is awesome and quite a piece of work. With it, I've been able to build an app that enables users to quickly access data they've inputted on my Drupal site from their iOS device (Android coming soon). However, I have developed coder's block and am stuck. Please see below.

Currently, my iOS app allows users to only look at information they've inputted on the Drupal site. I would like to give them the ability to edit the information from the device itself. However, this is challenging because the data on the site is entered using a webform and the view that provides the data for the app is built using webform submitted data. There is no node, that I know of, that contains the data for the view. As such, Drupal iOS SDK's nodeUpdate method isn't helpful. Furthermore, there is no viewUpdate and/or webform_submissionUpdate method, again that I know of, that I can use to enable editing from within the app. Do any of you know of any method or strategy that I could use to enable editing of the Drupal webform submitted data table from within an iOS app?  Put another way, any work being done to get a "webformsubmissionUpdate" or "submissionUpdate" method into the Drupal iOS SDK?  And, along those lines, any work being done to add a "Submission Update" resource added to the Drupal Services module?

Thank you in advance for your help and have a great day!!!

**Comment by kylebrowning** [comment]
If webform is using a particular content type (which it should be) you can use nodeUpdate. The setup I have right now is webform is its own content type so I can add new ones via nodeSave and update them via nodeUpdate.

Im not sure how your system is setup but if webform is storing the information in its own table, youll need to write a custom resource to pull that information out.

**Comment by Yiphi** [comment]
Thanks for all your help, Kyle--what you're saying makes complete sense.

I set up my Drupal site such that I have a webform content type.  I, the administrator, created a webform at node X.  Anytime an authenticated user (administrator or not) goes to this form, he/she will be able to input data that populates the webform_submitted_data table in my Drupal database.  The nid for all the data entries is X (same as node X).  No new nodes are created when a user submits his/her webform data at node X.  So, if each webform submission doesn't create a new node--and the administrator created the webform at node X--is it even possible for non-adminstrator authenticated users to edit the node (assuming they are not given full permissions for that node)?  Of note, I think I have done every possible permission permutation to try to make this happen, including CCK, Content Access module, Nodeaccess module, node specific access grants, etc.  And the reason I have gone down the permissions route is that whenever I use nodeGet, I don't get any access errors (nor do I see any of the data that was entered at node X for that user--rather, I see the descriptions for the webform's fields).  However, whenever I use nodeUpdate, I get a 401 error--regardless of whether I log in as the administrator or another authenticated (non-administrator) user.  Are my permission settings the culprit behind this 401 error?  Even if my node permissions for webforms are set correctly, would I still get this error because I'm trying to update a webform submission rather than a node (please see paragraph after sample code below)?  A sampling of my code is below:

NSMutableDictionary *nodeParams = [[NSMutableDictionary alloc] init];
[nodeParams setObject:@"X" forKey:@"nid"];

[DIOSNode nodeGet:nodeParams success:^(AFHTTPRequestOperation *operation, id responseObject){...--> no access errors; works fine; returns descriptions for the webform's fields and no submitted data

[DIOSNode nodeUpdate:nodeParams success:^(AFHTTPRequestOperation *operation, id responseObject){...--> fails with 401 error

I have looked into creating a custom resource per your recommendation.  I was going to try to adapt the code in the Services module that already exists for the node resource (update) so that it would update a submission rather than a node.  This is based on my suspicion that I need to update a submission since each webform submission results in a new sid but not a new nid (the nid is always X regardless of what the sid is).  My suspicion is also based on the fact that nodeGet returns the webform's field descriptions rather than any submitted data.  Am I thinking it about all this in the right way?

Since this issue has been closed, I'll open a new one.  I thank you in advance for your help and apologize if my question is elementary and/or if anything is unclear.  Take care and enjoy the rest of your Thanksgiving holiday!
