### ISSUE TITLE
nodeUpdate 401 error

### ISSUE THREAD

**Issue by Yiphi** [kylebrowning/drupal-ios-sdk#72]
Thanks for all your help, Kyle--what you're saying makes complete sense.

I set up my Drupal site such that I have a webform content type.  I, the administrator, created a webform at node X.  Anytime an authenticated user (administrator or not) goes to this form, he/she will be able to input data that populates the webform_submitted_data table in my Drupal database.  The nid for all the data entries is X (same as node X).  No new nodes are created when a user submits his/her webform data at node X.  So, if each webform submission doesn't create a new node--and the administrator created the webform at node X--is it even possible for non-adminstrator authenticated users to edit the node (assuming they are not given full permissions for that node)?  Of note, I think I have done every possible permission permutation to try to make this happen, including CCK, Content Access module, Nodeaccess module, node specific access grants, etc.  And the reason I have gone down the permissions route is that whenever I use nodeGet, I don't get any access errors (nor do I see any of the data that was entered at node X for that user--rather, I see the descriptions for the webform's fields).  However, whenever I use nodeUpdate, I get a 401 error--regardless of whether I log in as the administrator or another authenticated (non-administrator) user.  Are my permission settings the culprit behind this 401 error?  Even if my node permissions for webforms are set correctly, would I still get this error because I'm trying to update a webform submission rather than a node (please see paragraph after sample code below)?  What are the correct permissions in order for nodeUpdate to work properly?  A sampling of my code is below:

NSMutableDictionary *nodeParams = [[NSMutableDictionary alloc] init];
[nodeParams setObject:@"X" forKey:@"nid"];

[DIOSNode nodeGet:nodeParams success:^(AFHTTPRequestOperation *operation, id responseObject){...--> no access errors; works but returns descriptions for the webform's fields and not any submitted data

[DIOSNode nodeUpdate:nodeParams success:^(AFHTTPRequestOperation *operation, id responseObject){...--> fails with 401 error

I have looked into creating a custom resource per your recommendation.  I was going to try to adapt the code in the Services module that already exists for the node resource (update) so that it would update a submission rather than a node.  This is based on my suspicion that I need to update a submission since each webform submission results in a new sid but not a new nid (the nid is always X regardless of what the sid is).  My suspicion is also based on the fact that nodeGet returns the webform's field descriptions instead of any submitted data.  Am I thinking it about all this in the right way?

I thank you in advance for your help and apologize if my question is elementary and/or if anything is unclear.  Take care and enjoy the rest of your Thanksgiving holiday!

**Comment by Yiphi** [comment]
Hi Kyle--thanks for bearing with my rookie questions.

I decided that the best way for me to take care of this was by using an Xcode connection to my database using php.  Everything is working as I need it to now.

That being said, I'm not closing this issue because I still don't know why the 401 error was occurring with nodeUpdate and not nodeGet.  Additionally, I didn't solve this particular issue using Drupal iOS SDK.  If you feel like those issues are not useful questions and/or considerations, feel free to close this issue.

Thanks again for all your hard work managing/maintaining the Drupal iOS SDK and responding to my questions/issues.  Take care and enjoy the rest of your weekend!!

**Comment by kylebrowning** [comment]
I am still unable to replicate this.
