### ISSUE TITLE
Assign the responseObject from DIOSNode nodeGet to a variable 

### ISSUE THREAD

**Issue by onepartscissors** [kylebrowning/drupal-ios-sdk#73]
Hi Kyle

I hope you can help - i'm trying to understand how i can utilize the result retrieved by DIOSNode elsewhere in my code.

I am doing a very simple DIOSNode nodeGet as per the example, and it is working successfully; within the "[DIOSNode nodeGet:nodeData success" block of code i can access all the data of the Node that's been retrieved, but i now need to use this data elsewhere in my app - so i need to do something like the below - which doesn't work of course:

```
NSMutableDictionary *nodeData = [NSMutableDictionary new];
NSMutableDictionary *nodeDataReceived = [NSMutableDictionary new];
[nodeData setValue:@"1" forKey:@"nid"];
[DIOSNode nodeGet:nodeData success:^(AFHTTPRequestOperation *operation, id responseObject) {
    // Do Something with the responseObject
responseObject = nodeData;
} failure:^(AFHTTPRequestOperation *operation, NSError *error) {
       // error
}];
```

or perhaps:

```
nodeDataReceived = [DIOSNode nodeGet:nodeData success:^(AFHTTPRequestOperation *operation, id responseObject) {
    // Do Someth... etc, etc...
```

Can you guide me as to how to assign this data to a Dictionary or something? The reason being that i have this data retrieved from Drupal, but now need to use it in several places throughout the code, and it would be ideal if i could write the responseObject into a NSDictionary or something that i can access from different Methods and so on?

Hope this makes sense?

**Comment by kylebrowning** [comment]
Please use the issues for Drupal iOS SDK issues you are hving with DIOS.

That being said, you need to store the response object in a property or somewhere else so you can access wherever you need to.

I dont know the details of your application or what you need to do with the response, but do note that responseObject will be autoreleased so its best to store it in a new dictionary.
