### ISSUE TITLE
Howto login with email/password ?

### ISSUE THREAD

**Issue by loh-xx** [kylebrowning/drupal-ios-sdk#74]
Hello,

I've already used username/password method (DIOSUser.userLoginWithUsername) to log in Drupal services.
Please, can you tell me how to log in with email/password ?

Thank

**Comment by loh-xx** [comment]
I'm sorry, I've done it.

**Comment by shadow45** [comment]
Can you share with a sample of u're code source , i'm woriking on a project where Drupal is a backend and i'm working on the ios application .

some help please
