### ISSUE TITLE
node nodeAttachFile:fileData --- How to assign a role to a user

### ISSUE THREAD

**Issue by atomicaxis** [kylebrowning/drupal-ios-sdk#75]
Hi Kyle, thanks for all your work.

I was wondering how I could get my hands on [node nodeAttachFile:fileData]? I am wanting to attach pictures to nodes. This method is in the docs but nowhere to be found on git branches. I've seen you called it in a commented test which makes me think you have it implemented on your local copy.

Also, is it possible to set a role for a user?

I've tried the following which does not work:

```
NSMutableDictionary *userData = [NSMutableDictionary new];
NSString *drupalID = [[NSUUID UUID] UUIDString];
NSLog(@"drupalID: %@", drupalID);
NSString *drupalPassword = @"password";
[userData setValue:drupalID forKey:@"name"];
[userData setValue:[drupalID stringByAppendingString:@"@gmail.com"] forKey:@"mail"];
[userData setValue:drupalPassword forKey:@"pass"];

[DIOSUser userRegister:userData success:^(AFHTTPRequestOperation *operation, id responseObject) {
    NSLog(@"register user success");
    NSLog(@"%@", responseObject);
    [[NSUserDefaults standardUserDefaults] setObject:[responseObject objectForKey:@"uid"] forKey:@"kDrupalUserID"];
    [[NSUserDefaults standardUserDefaults] setObject:drupalID forKey:@"kDrupalUserName"];
    [[NSUserDefaults standardUserDefaults] setObject:drupalPassword forKey:@"kDrupalPassword"];
    [userData setValue:[responseObject objectForKey:@"uid"] forKey:@"uid"];
     [userData setObject:@{@"2" : @"authenticated user", @"5" : @"app user"} forKey:@"roles"];
     [DIOSUser userSave:userData success:^(AFHTTPRequestOperation *operation, id responseObject) {
     NSLog(@"success adding role");
     } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
     NSLog(@"failure adding role:%@", [error localizedDescription]);
     }];
```

**Comment by ianmen** [comment]
Did you find out about this issue ? I'm also having trouble uploading files

**Comment by atomicaxis** [comment]
No, I'm afraid that it's something that kyle b. has to push the missing code. I'm still stuck.. I've got an app in the store with pictures that are stored locally on the phone only because of that.

**Comment by kylebrowning** [comment]
Im not sure if I have this code still but let me look around through my local branches.

On the Services side It was committed to 3.x. http://drupal.org/node/1484992
