### ISSUE TITLE
inherited method and properties not found

### ISSUE THREAD

**Issue by hajderr** [kylebrowning/drupal-ios-sdk#76]
In DIOSSession.m I get several warnings

e.g. line 91

`[sharedSession setBaseURL:[NSURL URLWithString:url]];`

instance method -setBaseURL not found (return type defaults to id)

line 242

  `NSString *fixedURL = [self baseURLforAddress:url];`

some warning but method baseURL...

etc

**Comment by kylebrowning** [comment]
I think thats because the version of AFNetworking that your using doesnt have those methods. :(

**Comment by hajderr** [comment]
Actually I did remove the warnings by redeclaring the property in the .h file. There were also some prototype declarations missing.
