### ISSUE TITLE
Updated version Drupal iOS

### ISSUE THREAD

**Issue by ramosjeremy** [kylebrowning/drupal-ios-sdk#77]
I just recently tried to integrate the latest commit of Drupal iOS sdk with the latest version of AFNetworking 1.1.0 and found some build issues. AFNetworking no longer includes a setBaseURL method in the AFHTTPClient class. This method is called twice in the DIOSSession.m, per below. I have commented these calls out, and have also removed the release calls in order to be compatible with ARC. I did a simple test, but I am not sure of these changes.

I would like to know if you think these changes are safe? Also, if you can test these it might be good to release another version with these modifications.
- (DIOSSession _)sharedSessionWithURL:(NSString_)url {
  dispatch_once(&once, ^ {
    sharedSession = [[self alloc] initWithBaseURL:[NSURL URLWithString:url]];
    [sharedSession setParameterEncoding:AFJSONParameterEncoding];
  });
  //[sharedSession setBaseURL:[NSURL URLWithString:url]];
  return sharedSession;
  }
- (DIOSSession _)sharedOauthSessionWithURL:(NSString_)url consumerKey:(NSString *)aConsumerKey secret:(NSString *)aConsumerSecret {
  dispatch_once(&once, ^ {
    sharedSession = [[self alloc] initWithBaseURL:[NSURL URLWithString:url] consumerKey:aConsumerKey secret:aConsumerSecret];
    [sharedSession setParameterEncoding:AFJSONParameterEncoding];
  });
  //[sharedSession setBaseURL:[NSURL URLWithString:url]];
  return sharedSession;
  }

**Comment by kylebrowning** [comment]
Can you fork and submit a pull request for me to test?
