### ISSUE TITLE
userRegister returns error 406 when CAPTCHA enabled

### ISSUE THREAD

**Issue by Yiphi** [kylebrowning/drupal-ios-sdk#79]
Hi Kyle.

Drupal-iOS-SDK is stellar and working beautifully.  That being said, I am at the point where I would like users to be able to create an account from within the iOS app.  However, whenever I enable the CAPTCHA for the user registration form, the app returns a 406 HTML error.  Since I would like to only skip CAPTCHA on the registration form for all registrations that originate from within the app (i.e. user register web service), what do you think is the best solution?  I have tried to modify the hook_form_alter function in captcha.module but I don't think I'm modifying it correctly because it didn't fix the issue.  Of note, if I disable CAPTCHA on the registration form, I'm able to successfully create the user from within the app.

Thanks in advance for your help and enjoy the rest of your weekend!!!!!!!

**Comment by kylebrowning** [comment]
This has to do with captcha, not drupal-ios-sdk.
