### ISSUE TITLE
Potential Memory Leak in DIOSConnect.m 

### ISSUE THREAD

**Issue by ghost** [kylebrowning/drupal-ios-sdk#8]
Hello,

First I have to say I love to use DIOS . Good job.

The leak appears after saving a node for two or more times. In my projects and in you DiosDemoProject.

Last week I used instruments(leaks) to get possible memory leaks and it told me that there is a leaked object :
NSCFString      0x5c3eee0   32  CFNetwork   HTTPMessage::extractResponseStatusLine(unsigned char const*, long)

Extended Details told me that there is the leaked object has a connection to DiosNode.m:60 , DIOSConnect.m:159 and ASIHTTPRequest.m:762.

So have you ever seen that kind of memory leak ? And what can I do ?

I tried to get rid of the leak , but at the moment I have no idea .

Kind regards from Austria Europe ,
Florian

**Comment by kylebrowning** [comment]
I havnt see a leak like that.

I cant really handle any leaks with ASIHTTPRequest, unless its something IM specifically not allocating.

Which version of DIOS are you using?

**Comment by ghost** [comment]
I'am using your latest DIOS 6.x-2.x , the latest ASIHTTPRequest and IOS 4.2  with the example code and the leak occurs after saving or loading a node for more than one time. If you like I can send you a screenshoot of leaks ? Sorry but I have no idea how to fix that leak. Thx for your reply.
