### ISSUE TITLE
Can't seam to create a file or find Node Attach File method

### ISSUE THREAD

**Issue by estock** [kylebrowning/drupal-ios-sdk#80]
Hey Kyle, 

I've been using drupal-ios-sdk, and for displaying and creating certain drupal content without fail, I really appreciate what you have done here. When it comes to creating files, I've had no luck. Specifically, I'm trying to upload an video file (even small video files fail). I've read thought the documentation and it refers to Node Attach File, but no such method appears in the actual code. I wonder if you can provide an example of how to upload a large file (for instance a video file), it would save me hours of banging my head again the wall, and I'm sure it would be trivial for you.

Thanks

**Comment by estock** [comment]
it appears that this function does not exist in the master or dev branches, but rather it exists in a fork of the master branch. I finally was able to get it to work correctly, but I had to do some serious hacking on the services end (_FILES was posted with a completely different structure than Drupal expected)

**Comment by kylebrowning** [comment]
NodeAttachFile yeah, we dont have a working version in Services yet so WE cant expect this code in the DIOS to work.

**Comment by utneon** [comment]
Is this issue already solved in services?
