### ISSUE TITLE
DIOSession and oAuth

### ISSUE THREAD

**Issue by cquendangen** [kylebrowning/drupal-ios-sdk#81]
Hi, I'm a newbie so please pardon my rudimentary question.
I am trying to develop an app that would: (1)get real time posts from a drupal server, and (2)would force a user to login if they would like to post an entry into the website.
Now, for (1), will I need a DIOSession in order to do this using drupal ios sdk? It seems that establishing DIOSession would require some oAuth of some level (either 2-legged or 3-legged).
For (2), will this require a 3-legged oAuth? 

I downloaded the drupal ios sdk example from github, it seems that I need to modify some stuff to make it work. If there is a better example out there, please let me know.

Thanks in advance.

**Comment by kylebrowning** [comment]
You dont need to use oAUTH, you can use Session, oAuth is just a a security measure.

Its up to you which authentication method to use.
