### ISSUE TITLE
DIOS equivalent for Android?

### ISSUE THREAD

**Issue by loh-xx** [kylebrowning/drupal-ios-sdk#83]
Please can somebody tell me if there is DIOS equivalent for Android?
I google it but nothing.
Thank

**Comment by utneon** [comment]
https://github.com/INsReady/DrupalCloud

not good as DIOS but it's a starting point. I would do my own library and make it available in GitHub.

**Comment by loh-xx** [comment]
Thank you utneon.
When finishing your version, please let me know.

**Comment by kylebrowning** [comment]
https://github.com/workhabitinc/dandy But its nowhere near complete.
