### ISSUE TITLE
DIOSFlag and others

### ISSUE THREAD

**Issue by utneon** [kylebrowning/drupal-ios-sdk#84]
hey kylebrowning, I've developed some extra classes like DIOSFlag and DIOSFacebookOauth, what's the best way to contribute back that code

**Comment by kylebrowning** [comment]
I thnk the easiest way is for you to setup your own repository with them, and Ill link to it on the Wiki,

**Comment by utneon** [comment]
What do you want me to call the repository? DIOSContrib, DIOSExtra? Right now i have the DIOSFlag.m, DIOSFacebookOauth.m and I'm also working on DIOSVotingAPI and DIOSInAppPurchase.

Should i post documentation for those resources in this repo as well?

Thank you.

**Comment by kylebrowning** [comment]
Maybe just start an additional repo for people to commit to like, drupal-ios-sdk-addons, and name the classes whatever is appropriate.

**Comment by kylebrowning** [comment]
As for the docs, I would keep them with your code as people will not always have your code when downloading the Drupal iOS SDK, it would be extra documentation in this repo. I can and will link to in this README though.

**Comment by utneon** [comment]
Thank you for your suggetions, I will create very soon this repo and will notice you with the link. I'm an active Drupal Developer as well iOS developer, so you can count on me to help you build some extra DIOS resources.

**Comment by utneon** [comment]
check https://github.com/utneon/drupal-ios-sdk-addons, let me know if everything is ok with LICENSE and README files. Will do some documentation soon.

**Comment by kylebrowning** [comment]
Cool, it as been added!

**Comment by utneon** [comment]
Nice, I've developed this sandbox module, http://drupal.org/sandbox/utneon/1903856 will add some reference and documentation in drupal-ios-sdk-addons in a couple of days with some iOS example.
