### ISSUE TITLE
Use CocoaPods

### ISSUE THREAD

**Issue by mattt** [kylebrowning/drupal-ios-sdk#85]
[CocoaPods](http://cocoapods.org) is the standard means of packaging and managing dependencies for open source projects. Adopting it would greatly simplify the installation process, ensure future compatibility with AFNetworking, and expand the audience of this library.

All that would need to be done is to create a `.podspec` file and submit it to the CocoaPods/Specs repository.

**Comment by kylebrowning** [comment]
https://github.com/CocoaPods/Specs/tree/master/drupal-ios-sdk/2.0.2
