### ISSUE TITLE
nodeIndexWithPage not working

### ISSUE THREAD

**Issue by mading** [kylebrowning/drupal-ios-sdk#95]
Unless I choose no oauth for the api endpoint, nodeIndexWithPage is not working.

Return 404.

**Comment by quitequick** [comment]
I noticed this as well. I imagine its because in DIOSNode.m line 152 method: is set to DELETE! My guess is it should be GET. Hope you didn't lose any data!

**Comment by kylebrowning** [comment]
FIxed, thanks!
